#!/usr/bin/env bash
# Apply SERVE_LANE presets. Writes .env.lane (gitignored) for compose on head+worker.
# Sourced by scripts/up.sh after .env.
set -euo pipefail

_ROOT="${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

_resolve_host_path() {
  local p="$1"
  if [[ "$p" = /* ]]; then echo "$p"; return; fi
  if [[ "$p" == ../* ]]; then echo "$_ROOT/${p#../}"; return; fi
  echo "$_ROOT/$p"
}

lane="${SERVE_LANE:-golden}"
case "$lane" in
  golden|w4a16|"")
    export SERVE_LANE=golden
    export MODEL="${MODEL_GOLDEN:-canada-quant/glm-5.3-w4a16-mtp}"
    export GLM5NEXT_PATCH_HOST="${GLM5NEXT_PATCH_HOST_GOLDEN:-../patches/glm5next_model.py}"
    ;;
  modelopt|modelopt-w4a16-nvfp4|axiomofmind)
    export SERVE_LANE=modelopt
    export MODEL="${MODEL_MODELOPT:-axiomofmind/GLM-5.3-Flash-W4A16-NVFP4}"
    # Eagle3 for DFlash2 + ModelOpt ignore-aware dense/shared quant_config.
    export GLM5NEXT_PATCH_HOST="${GLM5NEXT_PATCH_HOST_MODELOPT:-../patches/glm5next_model.modelopt.py}"
    ;;
  *)
    echo "[lane] ERROR: unknown SERVE_LANE='$lane' (use golden|modelopt)" >&2
    return 1 2>/dev/null || exit 1
    ;;
esac

_resolved="$(_resolve_host_path "$GLM5NEXT_PATCH_HOST")"
if [[ ! -f "$_resolved" ]]; then
  echo "[lane] ERROR: GLM5NEXT_PATCH_HOST not found: $GLM5NEXT_PATCH_HOST ($_resolved)" >&2
  return 1 2>/dev/null || exit 1
fi

# Comment: compose --env-file on worker cannot see head shell exports — materialize.
cat > "$_ROOT/.env.lane" <<EOF
# generated by scripts/apply-serve-lane.sh — do not edit
SERVE_LANE=$SERVE_LANE
MODEL=$MODEL
GLM5NEXT_PATCH_HOST=$GLM5NEXT_PATCH_HOST
EOF

echo "[lane] SERVE_LANE=$SERVE_LANE"
echo "[lane] MODEL=$MODEL"
echo "[lane] GLM5NEXT_PATCH_HOST=$GLM5NEXT_PATCH_HOST"
echo "[lane] wrote $_ROOT/.env.lane"
